image: gradle:latest

stages:
  - build
  - test
  - release

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  BUILD_DIR: "build/libs"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x gradlew || true  # Ensure Gradle wrapper is executable

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - $BUILD_DIR/*.jar
    expire_in: 1 day
  only:
    - branches
    - tags

test:
  stage: test
  script:
    - ./gradlew test

release:
  stage: release
  script:
    - echo "Creating release..."
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG"
    assets:
      links:
        - name: "Jar"
          url: "https://gitlab.com/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/raw/$BUILD_DIR/*.jar"
  only:
    - tags
  dependencies:
    - build