# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=1.0.5+26.3
maven_group=net.rickiewars
archives_base_name=serverkit

# Fabric Properties
# check these on https://fabricmc.net/develop
# Minecraft ships unobfuscated as of 26.1, so there is no mappings dependency to configure.
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18.2

# Fabric API
fabric_version=0.160.7+26.3

# Mod Dependencies
# https://github.com/Patbox/polymer (in development support for unmodded clients)
polymer_version=0.18.1+26.3
# https://github.com/Patbox/common-economy-api
common_economy_api_version=2.0.0
# https://github.com/lucko/fabric-permissions-api
fabric_permissions_api_version=0.7.0

# For Unit Testing
# See the [fabric-loader-unit maven artifacts](https://mvnrepository.com/artifact/net.fabricmc/fabric-loader-junit)
# Select the version that matches the loader version (https://mvnrepository.com/artifact/net.fabricmc/fabric-loader-junit/<loader_version>)
# Check the runtime dependencies for the required platform version
junit_version=5.10.0
junit_platform_version=1.10.0

# Other dependencies
## Expression evaluator: https://github.com/ezylang/EvalEx
## Is under unit tests so just update & run the tests to check if it still works
evalex_version=3.5.0
